version: 2.1
jobs:
  build:
    working_directory: ~/scala-tsi
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - scala-tsi-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
            - scala-tsi-6

      - run:
          name: Compile and test for 2.13
          command:
            sbt -batch ++2.13.2 compile test:compile scala-tsi-macros/compile scala-tsi-macros/test:compile sbt-scala-tsi/compile sbt-scala-tsi/test:compile exit

      - run:
          name: Compile and test for 2.12
          command:
            sbt -batch ++2.12.11 compile test:compile scala-tsi-macros/compile scala-tsi-macros/test:compile sbt-scala-tsi/compile sbt-scala-tsi/test:compile exit

      - save_cache:
          key:  scala-tsi-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
          paths:
            - target/resolution-cache
            - target/streams
            - project/target/resolution-cache
            - project/target/streams
            - ~/.sbt
            - ~/.cache

      - save_cache:
        # Changing this key/incrementing the number at the end is the only way to remove old dependencies and/or generate a more up-to-date cache
          key: scala-tsi-6
          paths:
            - ~/.sbt
            - ~/.cache

      - run:
          name: Check formatting
          command:
            sbt scalafmtSbtCheck scalafmtCheckAll exit

      - run:
          command:
            sbt test scala-tsi-macros/test sbt-scala-tsi/test exit

      - store_test_results:
          path: target/test-reports

      - run:
          command:
            sbt -batch publishLocal sbt-scala-tsi/publishLocal

      - run:
          name: "test and generate example project"
          command: sbt -batch test generateTypescript scalafmtSbtCheck scalafmtCheckAll exit
          working_directory: example

      - run:
          name: "Check example project output"
          command: diff model.ts expected_model.ts
          working_directory: example
          
      - store_test_results:
          path: example/target/test-reports

      - store_artifacts:
          path: example/model.ts

  publish:
    working_directory: ~/scala-tsi
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - scala-tsi-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
            - scala-tsi-6

      - run:
          command:
            sbt -batch +publishSigned +sbt-scala-tsi/publishSigned

      # releases everything from com.scala-tsi, look into releasing only this project
      - run:
          command:
            sbt -batch "sonatypeReleaseAll com.scala-tsi"

  publish_codestar:
    working_directory: ~/scala-tsi
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout

      - restore_cache:
          keys:
            - scala-tsi-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
            - scala-tsi-6

      - run:
          command:
            sbt -batch +codestar/publishSigned +sbt-scala-tsi-codestar/publishSigned

      # releases everything from nl.codestar, look into releasing only this project
      - run:
          command:
            sbt -batch "sonatypeReleaseAll nl.codestar"

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/ # Only run for tagged builds
            tags:
              only: /[0-9].*/ # x.y.z version has that tag name
      - publish_codestar:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/ # Only run for tagged builds
            tags:
              only: /[0-9].*/ # x.y.z version has that tag name
