version: 2
jobs:
  build:
    working_directory: ~/scala-ts-interfaces
    docker:
      - image: codestar/circleci-scala-sbt-git:scala-2.12.4-sbt-1.0.2
    steps:
      - checkout

      - restore_cache:
          keys:
            - scala-ts-interfaces-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
            - scala-ts-interfaces-1

      - run:
          name: Compile
          command:
            sbt compile test:compile scala-tsi-macros/compile scala-tsi-macros/test:compile exit

      - save_cache:
          key: scala-ts-interfaces-{{ checksum "project/plugins.sbt" }}-{{ checksum "build.sbt" }}
          paths:
            - target/resolution-cache
            - target/streams
            - project/target/resolution-cache
            - project/target/streams
            - ~/.sbt
            - ~/.ivy2/cache
            - ~/.m2
      - save_cache:
        # Changing this key/incrementing the number at the end is the only way to remove old dependencies and/or generate a more up-to-date cache
          key: scala-ts-interfaces-1
          paths:
            - ~/.sbt
            - ~/.ivy2/cache
            - ~/.m2

      - run:
          name: Check formatting
          command:
            sbt scalafmt::test test:scalafmt::test sbt:scalafmt::test exit

      - run:
          command:
            sbt test scala-tsi-macros/test sbt-scala-tsi/publishLocal exit

      - store_test_results:
          path: target/test-reports

      - run:
          command:
            sbt publishLocal scala-tsi-macros/publishLocal sbt-scala-tsi/publishLocal

      - run:
          command: |
            cd example
            sbt test

      - store_test_results:
          path: example/target/test-reports
